---
- name: Install borgbackup
  ansible.builtin.yum:
    name: borgbackup
    state: present
- name: Create borg user
  ansible.builtin.user:
    name: borg
    state: present
    shell: /bin/bash
- name: Copy all public keys from clients
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp
    owner: root
    mode: 0600
  with_fileglob:
    - "files/backup/*.pub"
- name: Get list of public keys
  ansible.builtin.find:
    paths: /tmp
    pattern: "*.pub"
  register: pubkeys_list
- name: Read all public keys and prepend command to it
  ansible.builtin.command: awk '{$0="command=\"/usr/bin/borg serve\" " $0} 1' {{ item.path }}
  with_items: "{{ pubkeys_list.files }}"
  register: pubkeys_contents
- name: Write all lines to authorized_keys
  become: true
  ansible.builtin.lineinfile:
    path: /home/borg/.ssh/authorized_keys
    line: "{{ item.stdout }}"
  with_items: "{{ pubkeys_contents.results }}"