all:
  hosts:
    node1:
      ansible_host: 192.168.11.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/node1/virtualbox/private_key
    node2:
      ansible_host: 192.168.11.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/node2/virtualbox/private_key
    balancer:
      ansible_host: 10.0.10.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/balancer/virtualbox/private_key
    monitor:
      ansible_host: 172.16.1.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/monitoring/virtualbox/private_key
    firewall:
      ansible_host: 172.16.1.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/fw/virtualbox/private_key
    backup:
      ansible_host: 172.16.1.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../.vagrant/machines/backup/virtualbox/private_key
backends:
  hosts:
    node1: 
    node2:
frontends:
  hosts:
    balancer:
dbservers:
  hosts:
    node1:
      replication_role: master
      server_id: 1
    node2:
      replication_role: slave
      server_id: 2
monitoring:
  hosts:
    monitor:
logging:
  hosts:
    monitor:
monitored:
  hosts:
    node1:
    node2:
    monitor:
    firewall:
    balancer:
firewalls:
  hosts:
    firewall:
backup_servers:
  hosts:
    backup:
backup_clients:
  hosts:
    node2:
      backup_folder: "/var/backup/{{ wpdb_dbname }}/"