backends:
  hosts:
    back1:
      ansible_host: 192.168.53.2
    back2:
      ansible_host: 192.168.53.3
frontends:
  hosts:
    loadbalancer:
      ansible_host: 10.0.10.2
dbservers:
  hosts:
    db1:
      ansible_host: 192.168.53.2
      replication_role: master
      server_id: 1
    db2:
      ansible_host: 192.168.53.3
      replication_role: slave
      server_id: 2
monitoring:
  hosts:
    monitor:
      ansible_host: 172.16.1.2
logging:
  hosts:
    logger:
      ansible_host: 172.16.1.2
monitored:
  hosts:
    client1:
      ansible_host: 192.168.53.2
    client2:
      ansible_host: 192.168.53.3
    client3:
      ansible_host: 172.16.1.2
    client4:
      ansible_host: 172.16.1.3
    client5:
      ansible_host: 192.168.53.1
