---
- hosts: all
  roles:
    - { role: ntp_client, tags: ntp_client_tag, become: yes }
    - { role: general_settings, become: yes, tags: general }
# - hosts: all
#   gather_facts: false
#   tasks:
#     - set_fact:
#         control_node_ip: "{{ hostvars['127.0.0.1']['ansible_default_ipv4']['address'] }}"
#       run_once: true
#       delegate_to: localhost
#       delegate_facts: true
- hosts: frontends
  roles:
    - role: certs_gen
      tags: certs
    - role: frontend_nginx
      tags: front_tag
  become: yes
- hosts: backends
  become: yes
  roles:
    - role: backend_httpd
      tags: backend_httpd_tag
    - role: backend_php
    - role: backend_website
      tags: backend_website_tag
- hosts: dbservers
  become: yes
  roles:
    - role: dbserver
      tags: dbserver_tag
    - role: restore_wpbackup
      tags: restore_db_tag
- hosts: monitoring
  become: yes
  roles:
    - role: monitoring_server
      tags: monitoring_server_tag
- hosts: monitored
  become: yes
  roles:
    - role: monitored_node
      tags: monitored_node_tag
    - role: logging_node
      tags: logging_node_tag
