---
- hosts: all
  roles:
    - { role: ntp_client, tags: ntp_client_tag, become: yes }
    - { role: general_settings, become: yes, tags: general }
- hosts: frontends
  become: yes
  roles:
    - role: certs_gen
      tags: certs
    - role: frontend_nginx
      tags: front_tag
- hosts: backends
  become: yes
  roles:
    - role: backend_httpd
      tags: backend_httpd_tag
    - role: backend_php
    - role: backend_website
      tags: backend_website_tag
- hosts: backup_clients
  become: yes
  roles: 
    - role: backup_client
      tags: backup_cl_tag
- hosts: backup_servers
  become: yes
  roles:
    - role: backup_server
      tags: backup_srv_tag
- hosts: dbservers
  become: yes
  roles:
    - role: dbserver
      tags: dbserver_tag
    - role: restore_wpbackup
      tags: restore_db_tag
- hosts: monitored
  become: yes
  roles:
    - role: monitored_node
      tags: monitored_node_tag
    - role: logging_node
      tags: logging_node_tag
- hosts: backup_clients
  become: yes
  roles:
    - role: borg_autobackup
- hosts: firewalls
  become: yes
  roles:
    - role: fw_dmz
      tags: router_tag
- hosts: monitoring
  become: yes
  roles:
    - role: monitoring_server
      tags: monitoring_server_tag
    - role: logger_server
      tags: logger_tag