---
- hosts: localhost
  # vars:
  # contents: "{{ lookup('file', telegram_bot_token_file) }}"
  tasks:
    - set_fact:
        contents: "{{ lookup('file', telegram_bot_token_file) }}"
    - debug: msg="contents is {{ contents }}"
